### ISSUE TITLE
Error when building with Uglify/webpack

### ISSUE THREAD

**Issue by NatalieMac** [MaximVanhove/vue-router-back-button#1]
Uglify fails because it hits an error:

ERROR in static/js/vendor.js from UglifyJs
Unexpected token: punc (() [./~/vue-router-back-button/dist/index.js:1,822][static/js/vendor.js:66589,891]

**Comment by MaximVanhove** [comment]
I managed to reproduce the issue and will work on a fix

**Comment by MaximVanhove** [comment]
Issue fixed in vue-router-back-button@1.1.1
