### ISSUE TITLE
Erratic Behaviour on Nuxt 2.14.0 (Vue router 3.3.4)

### ISSUE THREAD

**Issue by eripoll** [MaximVanhove/vue-router-back-button#13]
Hi, 
I have installed your plugin using the provided instructions.
I have the following page structure
/feed -> /teams (no Back btn added there) -> /teams/_id (A back btn added there)

Back Btn component uses provided code:
```
    to () {
      if (this.client || !this.$routerHistory || !this.$routerHistory.hasPrevious()) {
        return { path: '/' }
      }

      return { path: this.$routerHistory.previous().path }
    }
```

Once on page /teams/_id and using BackBtn, I am taken to /feed.
If I try to navigate to another team page, same results
However, if once on Teams page I refresh entirely the app, the Back Btn takes back to another Teams page I visited previously.
Doesn't make any sense... Any idea?

**Comment by MaximVanhove** [comment]
Hi @eripoll,

Could you create a failing test case in router.spec.js? (You need to use node 8 to install and run the test suite)

Something like this:

```js
test('it goes back on dynamic pages', () => {
    push('/feed')
    push('/teams')
    push('/teams/1')

    expect(routerHistory.previous().path).toEqual('/teams')
})
```

**Comment by eripoll** [comment]
Hey, thank you for your reply, but the topic was kinda urgent, so I went in another direction.
Thanks!
