### ISSUE TITLE
Cant use this module

### ISSUE THREAD

**Issue by hedbisker** [MaximVanhove/vue-router-back-button#18]
I have do this npm install vue-router-back-button --save

![image](https://user-images.githubusercontent.com/5356674/162893699-bf2a2766-64db-47cd-a1c6-c1487c5109ea.png)

But, I cant use this module...

![image](https://user-images.githubusercontent.com/5356674/162893811-dcb84488-5973-4971-ad69-85a66d706eea.png)

What can I do?

**Comment by MaximVanhove** [comment]
`import VueRouterBackButton from 'vue-router-back-button'`
