### ISSUE TITLE
Not tracking history

### ISSUE THREAD

**Issue by sasokovacic** [MaximVanhove/vue-router-back-button#3]
Hi, I installed your plugin but it's not tracking history. I did all the installation steps and nothing. I'm using vue 2.5.17 and vue-router 3.0.2. Is it possible I forgot to set something? Or I'm just using it the wrong way...

**Comment by MaximVanhove** [comment]
Hello @sasokovacic ,

Did you add this to your router?

```
import Vue from 'vue'
import Router from 'vue-router'
import { routerHistory, writeHistory } from 'vue-router-back-button'

Vue.use(Router)
Vue.use(routerHistory)

const router = new Router({
    routes: []
})

router.afterEach(writeHistory)
export default router
```

**Comment by MaximVanhove** [comment]
I'm closing this issue as there is no answer since 2 months.
