### ISSUE TITLE
Issue with multiple route paths

### ISSUE THREAD

**Issue by pink-papaya** [MaximVanhove/vue-router-back-button#8]
Currently the history stores the next and previous routes so that we can call `.previous()` and `.next()` but this poses a problem when some routes may sometimes be skipped. 
If we programmatically move into a route in the future, the history does not acknowledge that we skipped routes and the `.previous()` route will not be the one where the user was previously.

For example, let´s say we have a route structure like this:
```
1 --- 2
 \   /
  1.1
```
And a user follows these steps:
- 1 -> 1.1 -> 2
History: [ "/1", "/1.1", "/2" ]

- 2 -> 1.1 -> 1 (go back)
History: [ "/1", "/1.1", "/2" ]

- 1 -> 2 (skipping 1.1)
History: [ "/1", "/1.1", "/2" ]
Go back will now take the user to /1.1 instead of /1

You can find a reproduction [here](https://codesandbox.io/s/vue-template-oij2t)

**Comment by MaximVanhove** [comment]
Hi @rnunot,

Thank you for the codesandbox. Going forward from 1 -> 2 should rewrite the history from that point. I'll be able to fix this.

**Comment by MaximVanhove** [comment]
Hi @rnunot,

This is fixed in 1.2.2

**Comment by pink-papaya** [comment]
Awesome, thanks for the quick response.
